
name: Terraform Plan

on:
  push:
    branches-ignore: [ main ]

jobs:
  aws:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'aws'

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate


      - name: Terraform Plan
        run: terraform plan

  azure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'azure'

    steps:
      - uses: actions/checkout@v3
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'azure'


      - name: Terraform validate
        run: terraform validate


      - name: Terraform Plan
        run: terraform plan
